const MAX_WIDTH = 1600;
const MAX_HEIGHT = 900;

export const PongSettings = {
MAX_WIDTH,
MAX_HEIGHT,
MAX_VEL: 10,
VEL_INCREMENT: 0.5,
BALL_SIZE: MAX_WIDTH * 0.0075,
PADDLE_WIDTH: MAX_WIDTH * 0.01,
PADDLE_SIZE: MAX_HEIGHT * 0.15,
PADDLE_OFFSET: 100,
PADDLE_VELOCITY: 1,
} as const;